---
driver:
  name: docker
  #volume: C:/chef:/etc/chef/

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
#  client_rb:
#    #audit_mode: :audit_only
#    log_level:        ":debug"
#    log_location:     "STDOUT"
#    ssl_verify_mode: ":no_verify"
#    chef_server_url:  "https://prod-chef-server-4plataforma.brazilsouth.cloudapp.azure.com/organizations/bigdata"
#    validation_client_name:  "bigdata-validator"
#    validation_key: "/etc/chef/bigdata-validator.pem"

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[zabbix-agent::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
